version: '3'
services:
  flask:
    build: .
    links:
      - mongo
    ports:
      - 5000:5000
    volumes:
      - ./static/Maps:/usr/src/app/static/Maps
    depends_on:
      - mongo
    command: python main.py

  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017

